<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-6D8FOT2J" failures="1" tests="3" name="Test" time="65.245" errors="0" timestamp="2024-12-01T19:45:01 IST">
  <testcase classname="tests.LoginTest" name="testValidLogin" time="0.012">
    <failure type="java.lang.AssertionError" message="Test case Failed">
      <![CDATA[java.lang.AssertionError: Test case Failed
at tests.LoginTest.testValidLogin(LoginTest.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testValidLogin -->
  <testcase classname="tests.LoginTest" name="testInvalidLogin" time="0.0">
    <skipped/>
  </testcase> <!-- testInvalidLogin -->
  <testcase classname="tests.LoginTest" name="SelectProductandCheckout" time="51.794"/>
</testsuite> <!-- Test -->
